### ISSUE TITLE
Add support for Redis

### ISSUE THREAD

**Issue by astorm** [astorm/Magento_CrossAreaSessions#2]
Redis is (likely) the next most popular session storage engine.  The project should support it. 

Also, I believe this will require adding a User.php class to the loader folder — if this is the caste User.php should also have a factory pattern applied so that multiple user level storage solutions (redit, memcache, etc.) are supportable.

**Comment by francosabolo** [comment]
Hi ! I have made a pull request which adds support for Redis. It has been developed and tested by me and my co-worker Bruno Mininno (https://github.com/brunomininno). We both work on ecloudsolutions.com in Rosario, Argentina. Hope it helps others like all your threads does.

Kind regards, Franco Sabolo.

**Comment by astorm** [comment]
Closing this out thanks to @francosabolo -- but if anyone runs into problems please reopen!
