### ISSUE TITLE
I can't seem to pull the active session

### ISSUE THREAD

**Issue by richardtwindom** [astorm/Magento_CrossAreaSessions#5]
I can't seem to find out what is going on - every time I load session data with getSessionData, it does not include a "user" element under the "admin" array.

It seems to be loading an empty session, rather than the one that is live in my browser.

Any ideas?

```php
require_once ('../app/Mage.php');
Mage::app(); 

// Ensure we're in the admin session namespace for checking the admin user..
Mage::getSingleton('core/session', array('name' => 'adminhtml'));

$adminhtml  = Mage::getModel('pulsestorm_crossareasession/manager')
->getSessionData('adminhtml'); 

var_export($adminhtml);
```

Output is:
`array ( 'core' => array ( '_session_validator_data' => array ( 'remote_addr' => '[[ip]]', 'http_via' => '', 'http_x_forwarded_for' => '', 'http_user_agent' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.85 Safari/537.36', ), 'session_hosts' => array ( 'mydomain.com' => true, ), ), 'admin' => array ( '_session_validator_data' => array ( 'remote_addr' => '[[ip]]', 'http_via' => '', 'http_x_forwarded_for' => '', 'http_user_agent' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.85 Safari/537.36', ), 'session_hosts' => array ( 'mydomain.com' => true, ), ), )`

The output is the same regardless of whether I have an admin session running or not.

Thanks in advance!

**Comment by astorm** [comment]
Not sure I understand the question/issue -- this looks like a command line script.  How can a command line script have a browser session?  

Or are you loading this as a web page?

Also, it looks like you're trying to explicitly load the `adminhtml` session -- if so, what would you need the cross area session module for?  Cross area session lets you load the `adminhtml` session from the frontend application, or load the `frontend` session from the backend.

**Comment by richardtwindom** [comment]
Loading this through a PHP file on the frontend - ultimate goal is to determine which admin user is logged in, if any.

**Comment by astorm** [comment]
The extension isn't designed to workout outside of a properly bootstrapped Magento environment -- the loading code in `Manager.php` and the two loader classes is pretty straight forward though, so if you discover the reason for your bug feel free to open another issue.
